language: ruby

before_install:
  - gem update bundler

rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.0

gemfile:
  - Gemfile
  - Gemfile.fluentd.0.10
  - Gemfile.fluentd.0.12

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.2.5
      gemfile: Gemfile.fluentd.0.10
    - rvm: 2.3.0
      gemfile: Gemfile.fluentd.0.10
